---
apiVersion: v1
kind: Service
metadata:
  labels:
    project: piggymetrics
    tier: backend
    app: statistics-service
  name: statistics-service
spec:
  ports:
  - name: http
    port: 7000
    targetPort: 7000
  selector:
    project: piggymetrics
    tier: backend
    app: statistics-service
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    project: piggymetrics
    tier: backend
    app: statistics-service
  name: statistics-service
spec:
  selector:
    matchLabels:
      app: statistics-service
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        project: piggymetrics
        tier: backend
        app: statistics-service
    spec:
      containers:
      - env:
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: piggymetrics
              key: config_service_password
        - name: STATISTICS_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: piggymetrics
              key: statistics_service_password
        - name: MONGODB_DATABASE
          valueFrom:
            secretKeyRef:
              name: piggymetrics
              key: mongodb_database
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: piggymetrics
              key: mongodb_uri
        - name: RABBITMQ_HOST
          valueFrom:
            secretKeyRef:
              name: piggymetrics
              key: rabbitmq_host
        - name: RABBITMQ_PORT
          valueFrom:
            secretKeyRef:
              name: piggymetrics
              key: rabbitmq_port
        - name: RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: piggymetrics
              key: rabbitmq_username
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: piggymetrics
              key: rabbitmq_password
        ports:
          - containerPort: 7000
        image: ${CONTAINER_REGISTRY}.azurecr.io/piggymetrics-statistics-service:${IMAGE_TAG}
        name: statistics-service
        resources: {}
      restartPolicy: Always
status: {}